### ISSUE TITLE
Consider using Pyscript

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/rst-playground#3]
[Pyscript](https://pyscript.net) provides a `<py-script>` HTML element that could make the code a little more readable. It relies on Pyodide underneath, so no functionality would be lost.

**Comment by not-my-profile** [comment]
I wouldn't pull in an additional dependency for something that doesn't benefit users at all.

**Comment by waldyrious** [comment]
Right. This could be justifiable if the entire code was in the index file, but now that it's been split to separate CSS and JS files (#9), there isn't much benefit indeed. I'll close this.
