### ISSUE TITLE
Convert index.html to XHTML

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/rst-playground#8]
I had initially created the page as a XHTML document, but had to go back to basic HTML because the iframe injection interfered with that. Once the conversion code is working properly, I'd like to investigate going back to XHTML, just to have an extra layer of code structure checking (the browser complains if the document is malformed).

The change would be simply renaming `index.html` to `index.xhtml`, and changing `<html>` to `<html xmlns="http://www.w3.org/1999/xhtml" lang="en">`

Relevant code:
https://github.com/waldyrious/rst-playground/blob/f8698e0d0c33e1bfe324e1e126884e388bacf6d3/index.html#L2

**Comment by not-my-profile** [comment]
The browser is complaining because of the missing doctype in the iframe ... the `<!doctype html>` works just fine.
